### PR TITLE
[cleanup] use default initializers for member variables

### PR DESCRIPTION
**Pull request by svenfoo**
Just a minor cleanup. Mainly opened this pull request to check if the AppVeyor build is broken here as well or just on #55

### CODE REVIEW

**Comment by AlwinEsch** [comment]
The AppVeyor Problem on Leia should be fixed with them https://github.com/xbmc/xbmc/pull/17276.

Good cleanup :smile:

**Comment by phunkyfish** [comment]
@svenfoo do you want to combine the two PRs yourself or merge them separately?

**Comment by svenfoo** [comment]
> @svenfoo do you want to combine the two PRs yourself or merge them separately?

I'm usually advocating for many small commits and since the changes are mostly unrelated I would prefer to see them merged separately.

**Comment by phunkyfish** [comment]
Small commits for sure. But PR wise that does not matter really, it just means a rebase after the first one is merged. All the commits in one PR avoids that.

Up to you.

**Review by phunkyfish — APPROVED** [review]
Will merge once appveyor completes.

**Pull request merged**
