### PR TITLE
[ios] Fix usage of sed

### PR DESCRIPTION
**Pull request by fetzerch**
This might not completely fix it, but should bring us one step closer.

### CODE REVIEW

**Comment by fetzerch** [comment]
New error: http://jenkins.kodi.tv/job/IOS/8055/consoleFull

```
[100%] Linking CXX shared library inputstream.rtmp.dylib
/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/buildtools-native/bin/cmake -E cmake_link_script CMakeFiles/inputstream.rtmp.dir/link.txt --verbose=1
/Applications/Xcode6.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -no-cpp-precomp  -arch armv7 -miphoneos-version-min=5.1 -std=c++11 -stdlib=libc++ -g -O2 -std=gnu++11 -isysroot /Applications/Xcode6.1.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk  -O3 -DNDEBUG -isysroot /Applications/Xcode6.1.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -dynamiclib -Wl,-headerpad_max_install_names  -Wl,-search_paths_first -Wl,-segalign,4000 -L/usr/lib/system -arch armv7 -miphoneos-version-min=5.1 -isysroot /Applications/Xcode6.1.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -stdlib=libc++   -compatibility_version 17.0.0 -current_version 1.0.0 -o inputstream.rtmp.1.0.0.dylib -install_name /Users/Shared/jenkins/workspace/IOS/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/inputstream.rtmp-prefix/src/inputstream.rtmp-build/inputstream.rtmp.17.0.dylib CMakeFiles/inputstream.rtmp.dir/src/RTMPStream.cpp.o /Users/Shared/jenkins/workspace/IOS/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/build/depends/lib/librtmp.a -lssl -lcrypto -lz 
ld: library not found for -lssl
```

almost ;)

**Comment by wsnipex** [comment]
this is still happening, see http://jenkins.kodi.tv/job/IOS/8149/consoleText

**Comment by akva2** [comment]
fixed the linker error.

there is no pkg-config for certain platforms, and the librtmp find resolves to the full path to the .a file, and no -L.

fixed this by manually looking for openssl in the add-on and appending the necessary include / link stuff.

**Comment by akva2** [comment]
and gave zlib the same treatment.

**Pull request merged**
