### PR TITLE
fix sync-addon-metadata-translations.yml

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Jenkins error unrelated to here!

**Comment by gade01** [comment]
This line will make it work: https://github.com/xbmc/inputstream.rtmp/pull/92/files#diff-687145e7b798c2310126b10cefeb5f179695e8151a273ca4db066212973c45aaR7

All other changes are unnecessary and the "old version" of the workflow. :)

**Comment by AlwinEsch** [comment]
Ups, thought that with change to
```
-          python -m pip install git+https://github.com/xbmc/sync_addon_metadata_translations.git
+          python -m pip install sync_addon_metadata_translations/
```
is change to new as looks a bit more clean :sweat:

**Comment by gade01** [comment]
No worries, both ways will work fine ;)

**Pull request merged**
