### PR TITLE
remove ununsed dependency on p8-platform

### PR DESCRIPTION
**Pull request by wsnipex**

### CODE REVIEW

**Comment by Rechi** [comment]
The following lines have to be removed too.
https://github.com/xbmc/inputstream.rtmp/blob/4b8ccf55ec5353f2f39c10dd90240271d85fbe37/CMakeLists.txt#L13-L14

**Comment by wsnipex** [comment]
looks like CI is not happy, what now?

**Comment by Rechi** [comment]
The [rtmp find module](https://github.com/xbmc/inputstream.rtmp/blob/Leia/FindRTMP.cmake) is broken.

**Comment by wsnipex** [comment]
closing in favor of https://github.com/xbmc/inputstream.rtmp/pull/54

**Pull request closed without merging**
